version: "3.9"
services:
  mongo:
    image: mongo:4.4.6
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - mynetwork

  fast_api:
    container_name: aflot
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/Aflot_backend_FastAPI
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  starlette_admin:
    container_name: starlette_admin
    build:
      context: .
      dockerfile: ./Dockerfile_admin
    ports:
      - "8001:8000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge